/**
 * T-003 Half B — source-side selector scanner.
 *
 * Walks target project JSX/TSX source and flags:
 *   - <input> without name="" or data-testid=""
 *   - <button onClick={...}> inside .map() without data-testid or key-derivable attr
 *
 * Outputs a structured list; the CLI renders it as SELECTOR_GAPS.md.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { Project, SyntaxKind, Node, JsxOpeningElement, JsxSelfClosingElement } from 'ts-morph'

export interface SelectorGap {
  file: string
  line: number
  col: number
  element: string
  issue: string
  suggestion: string
}

const JSX_FILE_RE = /\.[cm]?[tj]sx?$/

function collectSourceFiles(dir: string): string[] {
  const out: string[] = []
  function walk(d: string): void {
    let entries: fs.Dirent[]
    try {
      entries = fs.readdirSync(d, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      if (e.name === 'node_modules' || e.name === '.git' || e.name === 'dist') continue
      const full = path.join(d, e.name)
      if (e.isDirectory()) {
        walk(full)
      } else if (e.isFile() && JSX_FILE_RE.test(e.name)) {
        out.push(full)
      }
    }
  }
  walk(dir)
  return out
}

/** Check if a JSX element has a given attribute (with any value). */
function hasAttr(el: JsxOpeningElement | JsxSelfClosingElement, ...names: string[]): boolean {
  const attrs = el.getAttributes()
  for (const attr of attrs) {
    if (!Node.isJsxAttribute(attr)) continue
    const name = attr.getNameNode().getText()
    if (names.includes(name)) return true
  }
  return false
}

/** True if the node is a direct child of a .map() callback. */
function insideMapCallback(node: Node): boolean {
  let cur: Node | undefined = node.getParent()
  while (cur) {
    if (Node.isCallExpression(cur)) {
      const expr = cur.getExpression()
      if (Node.isPropertyAccessExpression(expr) && expr.getName() === 'map') return true
    }
    cur = cur.getParent()
  }
  return false
}

/** True if button has an onClick prop. */
function hasOnClick(el: JsxOpeningElement | JsxSelfClosingElement): boolean {
  return hasAttr(el, 'onClick', 'onPress')
}

export function scanSourceFile(filePath: string): SelectorGap[] {
  const source = fs.readFileSync(filePath, 'utf8')
  // Only process files that have JSX content
  if (!/<[A-Za-z]/.test(source)) return []

  const project = new Project({ useInMemoryFileSystem: true, skipFileDependencyResolution: true })
  const sf = project.createSourceFile('__scan__.tsx', source, { overwrite: true })
  const gaps: SelectorGap[] = []

  function addGap(el: JsxOpeningElement | JsxSelfClosingElement, issue: string, suggestion: string): void {
    const pos = el.getStart()
    const { line, column } = sf.getLineAndColumnAtPos(pos)
    gaps.push({
      file: filePath,
      line,
      col: column,
      element: el.getTagNameNode().getText(),
      issue,
      suggestion,
    })
  }

  sf.forEachDescendant((node) => {
    if (
      !Node.isJsxOpeningElement(node) &&
      !Node.isJsxSelfClosingElement(node)
    ) return

    const el = node as JsxOpeningElement | JsxSelfClosingElement
    const tag = el.getTagNameNode().getText().toLowerCase()

    // ── input without name or data-testid ─────────────────────────────────
    if (tag === 'input') {
      if (!hasAttr(el, 'name', 'data-testid')) {
        addGap(
          el,
          '<input> missing name="" or data-testid=""',
          'Add name="<field-name>" or data-testid="<field-id>" to make it addressable by test selectors',
        )
      }
    }

    // ── button with onClick inside .map() without data-testid ──────────────
    if (tag === 'button' && hasOnClick(el) && !hasAttr(el, 'data-testid') && insideMapCallback(node)) {
      addGap(
        el,
        '<button onClick> inside .map() without data-testid',
        'Add data-testid={`<prefix>-${item.id}`} to allow unambiguous selection in tests',
      )
    }
  })

  return gaps
}

export interface ScanDirResult {
  gaps: SelectorGap[]
  filesScanned: number
  filesWithGaps: number
}

export function scanSourceDir(dir: string): ScanDirResult {
  const files = collectSourceFiles(path.resolve(dir))
  let gaps: SelectorGap[] = []
  const withGaps = new Set<string>()
  for (const f of files) {
    const g = scanSourceFile(f)
    if (g.length > 0) {
      gaps = gaps.concat(g)
      withGaps.add(f)
    }
  }
  return { gaps, filesScanned: files.length, filesWithGaps: withGaps.size }
}

export function formatSelectorGapsMd(result: ScanDirResult, projectDir: string): string {
  const lines: string[] = [
    '# SELECTOR_GAPS.md',
    '',
    `> Generated by \`tester scan-selectors\`. ${result.gaps.length} gap(s) across ${result.filesWithGaps}/${result.filesScanned} file(s).`,
    '',
  ]
  if (result.gaps.length === 0) {
    lines.push('✓ No selector gaps detected.')
    return lines.join('\n')
  }
  const byFile = new Map<string, SelectorGap[]>()
  for (const g of result.gaps) {
    const rel = path.relative(projectDir, g.file)
    const arr = byFile.get(rel) ?? []
    arr.push(g)
    byFile.set(rel, arr)
  }
  for (const [rel, fileGaps] of byFile) {
    lines.push(`## ${rel}`)
    lines.push('')
    for (const g of fileGaps) {
      lines.push(`- **L${g.line}:${g.col}** \`<${g.element}>\` — ${g.issue}`)
      lines.push(`  → ${g.suggestion}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}
