/**
 * Audit-Suite Module A — Aviz (Delivery Note) PDF fixture generator.
 *
 * An "aviz de însoțire a mărfii" is the Romanian delivery receipt that
 * accompanies goods — used in 4-way-match scenarios (PO → GR → Invoice → Aviz).
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import * as fs from 'node:fs'
import * as path from 'node:path'
import * as crypto from 'node:crypto'

export interface AvizLineItem {
  sku: string
  description: string
  quantity: number
  unit?: string
}

export interface AvizOptions {
  out: string
  lines?: AvizLineItem[]
  avizNumber?: string
  supplierName?: string
  receiverName?: string
  linkedTo?: string // path to linked invoice PDF
}

// pdf-lib StandardFonts only cover WinAnsi (Latin-1). Strip combining diacritics and
// replace any remaining non-Latin-1 code-points with '?' so drawText never throws on
// user-supplied strings like Romanian company names.
function toWinAnsi(s: string): string {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^\x00-\xFF]/g, '?')
}

function randomAvizNumber(): string {
  const year = new Date().getFullYear()
  const seq = Math.floor(Math.random() * 9000) + 1000
  return `AVZ-${year}-${seq}`
}

export async function generateAvizPdf(opts: AvizOptions): Promise<void> {
  const avizNumber = opts.avizNumber ?? randomAvizNumber()
  const supplierName = opts.supplierName ?? 'Test Supplier SRL'
  const receiverName = opts.receiverName ?? 'Test Buyer Co.'
  const today = new Date().toISOString().split('T')[0]

  let lines = opts.lines ?? []
  if (lines.length === 0) {
    lines = [{ sku: 'ITEM-001', description: 'Product delivered', quantity: 10, unit: 'pcs' }]
  }

  const doc = await PDFDocument.create()
  const page = doc.addPage([595, 842])
  const helvetica = await doc.embedFont(StandardFonts.Helvetica)
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold)

  const { width } = page.getSize()
  let y = 800

  // Header
  // WinAnsi-safe: Ț→T, Ă→A (non-standard Latin diacritics not in Helvetica encoding)
  page.drawText('AVIZ DE INSOTIRE A MARFII', {
    x: 50, y, font: helveticaBold, size: 18, color: rgb(0.1, 0.4, 0.1),
  })
  page.drawText(toWinAnsi(avizNumber), { x: width - 200, y, font: helvetica, size: 11, color: rgb(0.3, 0.3, 0.3) })
  y -= 20
  page.drawText(`Data: ${today}`, { x: width - 200, y, font: helvetica, size: 10, color: rgb(0.3, 0.3, 0.3) })
  y -= 40

  page.drawText('Furnizor:', { x: 50, y, font: helveticaBold, size: 10 })
  page.drawText(toWinAnsi(supplierName), { x: 105, y, font: helvetica, size: 10 })
  page.drawText('Primitor:', { x: 300, y, font: helveticaBold, size: 10 })
  page.drawText(toWinAnsi(receiverName), { x: 355, y, font: helvetica, size: 10 })
  y -= 40

  // Column headers
  page.drawRectangle({ x: 50, y: y - 4, width: width - 100, height: 18, color: rgb(0.85, 0.92, 0.85) })
  page.drawText('Cod', { x: 55, y, font: helveticaBold, size: 9 })
  page.drawText('Denumire', { x: 110, y, font: helveticaBold, size: 9 })
  page.drawText('Cantitate', { x: 380, y, font: helveticaBold, size: 9 })
  page.drawText('UM', { x: 460, y, font: helveticaBold, size: 9 })
  y -= 22

  for (const line of lines) {
    page.drawText(toWinAnsi(line.sku), { x: 55, y, font: helvetica, size: 9 })
    page.drawText(toWinAnsi(line.description.slice(0, 45)), { x: 110, y, font: helvetica, size: 9 })
    page.drawText(String(line.quantity), { x: 390, y, font: helvetica, size: 9 })
    page.drawText(toWinAnsi(line.unit ?? 'buc'), { x: 460, y, font: helvetica, size: 9 })
    y -= 16
  }

  y -= 20
  page.drawLine({ start: { x: 50, y }, end: { x: width - 50, y }, thickness: 0.5, color: rgb(0.6, 0.6, 0.6) })

  // Signature blocks
  y -= 30
  page.drawText('Expeditor _______________', { x: 50, y, font: helvetica, size: 9 })
  page.drawText('Primitor _______________', { x: 300, y, font: helvetica, size: 9 })

  // Linked invoice reference
  if (opts.linkedTo) {
    y -= 30
    page.drawText(`Factura asociata: ${path.basename(opts.linkedTo)}`, {
      x: 50, y, font: helvetica, size: 9, color: rgb(0.4, 0.4, 0.4),
    })
    if (fs.existsSync(opts.linkedTo)) {
      const hash = crypto.createHash('sha256').update(fs.readFileSync(opts.linkedTo)).digest('hex').slice(0, 16)
      y -= 12
      page.drawText(`Invoice SHA-256 (first 16): ${hash}`, {
        x: 50, y, font: helvetica, size: 8, color: rgb(0.5, 0.5, 0.5),
      })
    }
  }

  page.drawText('Generated by @aledan007/tester fixtures -- test document, no legal value.', {
    x: 50, y: 30, font: helvetica, size: 7, color: rgb(0.6, 0.6, 0.6),
  })

  const outPath = path.resolve(opts.out)
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, await doc.save())
}
