/**
 * T-A1 — `tester init <feature>` scaffolder.
 *
 * Produces a runnable test skeleton for a new feature so session-start
 * Claude / TWG / pipelines all land on the same shape:
 *
 *   <project>/
 *     coverage/
 *       features.yaml          ← index of all features (auto-added here)
 *       <feature>.yaml         ← T-002 coverage matrix stub
 *     tests/<feature>/
 *       index.spec.ts          ← vitest skeleton with selfcheck import + teardown
 *       README.md              ← scenarios + how-to-run notes
 *
 * Pure file generation; no network calls. Tests feed a temp dir and
 * assert layout + content contracts.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import * as yaml from 'js-yaml'

export interface InitOptions {
  feature: string
  projectRoot: string
  owner?: string
  overwrite?: boolean
  withLogin?: boolean
}

export interface InitResult {
  feature: string
  projectRoot: string
  filesWritten: string[]
  filesSkipped: string[]
  featuresIndex: string
}

const FEATURE_SLUG_RE = /^[a-z0-9][a-z0-9-]{0,59}$/

export function assertFeatureSlug(feature: string): void {
  if (!FEATURE_SLUG_RE.test(feature)) {
    throw new Error(
      `feature slug "${feature}" invalid — use lowercase letters, digits, hyphens; starts with a letter/digit; max 60 chars.`,
    )
  }
}

function writeIfAllowed(
  file: string,
  content: string,
  overwrite: boolean,
  filesWritten: string[],
  filesSkipped: string[],
): void {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  if (fs.existsSync(file) && !overwrite) {
    filesSkipped.push(file)
    return
  }
  fs.writeFileSync(file, content, 'utf8')
  filesWritten.push(file)
}

export function renderCoverageYaml(feature: string, owner: string): string {
  const data = {
    feature,
    owner,
    scenarios: [
      {
        id: 'A1',
        name: 'smoke — feature entrypoint responds',
        category: 'smoke',
        severity: 'high',
        covered_by: null,
        status: 'missing',
      },
      {
        id: 'A2',
        name: 'auth negative — unauthenticated user gets 401',
        category: 'auth',
        severity: 'high',
        covered_by: null,
        status: 'missing',
      },
      {
        id: 'A3',
        name: 'happy path — create/read roundtrip',
        category: 'crud',
        severity: 'medium',
        covered_by: null,
        status: 'missing',
      },
    ],
  }
  return yaml.dump(data, { lineWidth: 120, noRefs: true })
}

export function renderSpecFile(feature: string, withLogin: boolean): string {
  const lines: string[] = []
  lines.push(`// Auto-generated by \`tester init ${feature}\` (T-A1). Customize freely.`)
  lines.push(`import { describe, it, expect, beforeAll, afterAll } from 'vitest'`)
  lines.push(`import { runSelfCheck, exitCodeForSummary } from '@aledan007/tester/self-test'`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Baseline harness check. If this fails, treat it as a HARNESS_BUG and do`)
  lines.push(` * NOT classify downstream failures as product bugs until resolved.`)
  lines.push(` */`)
  lines.push(`beforeAll(() => {`)
  lines.push(`  const summary = runSelfCheck()`)
  lines.push(`  const code = exitCodeForSummary(summary)`)
  lines.push(`  if (code >= 2) {`)
  lines.push(`    throw new Error('harness self-check failed — fix Tester before running this feature')`)
  lines.push(`  }`)
  lines.push(`})`)
  lines.push(``)
  lines.push(`// Track artefacts created during the suite; teardown removes them so`)
  lines.push(`// re-runs are deterministic.`)
  lines.push(`const createdIds: string[] = []`)
  lines.push(``)
  lines.push(`afterAll(async () => {`)
  lines.push(`  for (const id of createdIds.splice(0)) {`)
  lines.push(`    // TODO(${feature}): delete artefact by id — wire to app API`)
  lines.push(`    void id`)
  lines.push(`  }`)
  lines.push(`})`)
  lines.push(``)
  if (withLogin) {
    lines.push(`// Env-driven auth. Tests that hit protected routes call \`login()\` before`)
    lines.push(`// the first assertion and pass the returned token/session as needed.`)
    lines.push(`async function login(): Promise<{ token: string }> {`)
    lines.push(`  const base = process.env.TEST_BASE_URL || 'http://localhost:3000'`)
    lines.push(`  const email = process.env.TEST_EMAIL`)
    lines.push(`  const password = process.env.TEST_PASSWORD`)
    lines.push(`  if (!email || !password) {`)
    lines.push(`    throw new Error('TEST_EMAIL / TEST_PASSWORD are required for ${feature} suite')`)
    lines.push(`  }`)
    lines.push(`  const res = await fetch(\`\${base}/api/auth/login\`, {`)
    lines.push(`    method: 'POST',`)
    lines.push(`    headers: { 'Content-Type': 'application/json' },`)
    lines.push(`    body: JSON.stringify({ email, password }),`)
    lines.push(`  })`)
    lines.push(`  if (!res.ok) throw new Error(\`login failed: \${res.status}\`)`)
    lines.push(`  const body = (await res.json()) as { token?: string }`)
    lines.push(`  if (!body.token) throw new Error('login returned no token')`)
    lines.push(`  return { token: body.token }`)
    lines.push(`}`)
    lines.push(``)
  }
  lines.push(`describe('${feature} — coverage smoke', () => {`)
  lines.push(`  // A1 smoke — feature entrypoint responds`)
  lines.push(`  it.skip('A1: smoke — entrypoint responds', async () => {`)
  lines.push(`    // TODO(${feature}): replace with real endpoint / page check`)
  lines.push(`    expect(true).toBe(true)`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  // A2 auth negative — unauthenticated user gets 401`)
  lines.push(`  it.skip('A2: auth negative — unauth → 401', async () => {`)
  lines.push(`    // TODO(${feature}): replace URL with protected endpoint`)
  lines.push(`    const base = process.env.TEST_BASE_URL || 'http://localhost:3000'`)
  lines.push(`    const res = await fetch(\`\${base}/api/${feature}\`)`)
  lines.push(`    expect(res.status).toBe(401)`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  // A3 happy path — create/read roundtrip`)
  lines.push(`  it.skip('A3: happy path — create/read roundtrip', async () => {`)
  if (withLogin) {
    lines.push(`    const { token } = await login()`)
  }
  lines.push(`    // TODO(${feature}): call POST + GET, push created id into createdIds`)
  lines.push(`    expect(true).toBe(true)`)
  if (withLogin) {
    lines.push(`    void token`)
  }
  lines.push(`  })`)
  lines.push(`})`)
  lines.push(``)
  return lines.join('\n')
}

export function renderReadme(feature: string, owner: string): string {
  return [
    `# ${feature} — Feature test suite`,
    ``,
    `**Owner:** ${owner}`,
    `**Generated by:** \`tester init ${feature}\` (T-A1)`,
    ``,
    `## Scenarios (see \`coverage/${feature}.yaml\`)`,
    ``,
    `- **A1** smoke — feature entrypoint responds (severity: high)`,
    `- **A2** auth negative — unauthenticated user gets 401 (severity: high)`,
    `- **A3** happy path — create/read roundtrip (severity: medium)`,
    ``,
    `Add more scenarios by editing the coverage YAML + appending \`it.skip(...)\``,
    `blocks in \`index.spec.ts\`. Flip from \`skip\` to \`it\` once wired.`,
    ``,
    `## Running`,
    ``,
    `\`\`\`bash`,
    `TEST_BASE_URL=http://localhost:3000 \\`,
    `TEST_EMAIL=... TEST_PASSWORD=... \\`,
    `npx vitest run tests/${feature}`,
    `\`\`\``,
    ``,
    `## Verifying coverage`,
    ``,
    `\`\`\`bash`,
    `npx @aledan007/tester coverage --feature coverage/${feature}.yaml`,
    `npx @aledan007/tester untested --project .`,
    `\`\`\``,
    ``,
    `## Self-healing`,
    ``,
    `The \`beforeAll\` hook runs \`runSelfCheck()\` from Tester before the suite;`,
    `if the harness itself is broken (invalid selector, timing primitives, etc.)`,
    `tests will halt with a clear message rather than false-failing the product.`,
    ``,
  ].join('\n')
}

export interface FeaturesIndexEntry {
  feature: string
  owner: string
  coverage_file: string
  spec_file: string
  added_at: string
}

export interface FeaturesIndex {
  features: FeaturesIndexEntry[]
}

export function loadFeaturesIndex(projectRoot: string): FeaturesIndex {
  const file = path.join(projectRoot, 'coverage', 'features.yaml')
  if (!fs.existsSync(file)) return { features: [] }
  try {
    const parsed = yaml.load(fs.readFileSync(file, 'utf8')) as FeaturesIndex | null
    if (!parsed || !Array.isArray(parsed.features)) return { features: [] }
    return parsed
  } catch {
    return { features: [] }
  }
}

export function upsertFeaturesIndex(
  projectRoot: string,
  entry: FeaturesIndexEntry,
): string {
  const file = path.join(projectRoot, 'coverage', 'features.yaml')
  const index = loadFeaturesIndex(projectRoot)
  const existingIdx = index.features.findIndex((e) => e.feature === entry.feature)
  if (existingIdx >= 0) {
    index.features[existingIdx] = { ...index.features[existingIdx], ...entry }
  } else {
    index.features.push(entry)
  }
  index.features.sort((a, b) => a.feature.localeCompare(b.feature))
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, yaml.dump(index, { lineWidth: 120, noRefs: true }), 'utf8')
  return file
}

export function initFeature(opts: InitOptions): InitResult {
  assertFeatureSlug(opts.feature)
  const root = path.resolve(opts.projectRoot)
  if (!fs.existsSync(root)) {
    throw new Error(`project root does not exist: ${root}`)
  }
  const owner = opts.owner || path.basename(root)
  const filesWritten: string[] = []
  const filesSkipped: string[] = []

  const coverageFile = path.join(root, 'coverage', `${opts.feature}.yaml`)
  writeIfAllowed(
    coverageFile,
    renderCoverageYaml(opts.feature, owner),
    !!opts.overwrite,
    filesWritten,
    filesSkipped,
  )

  const testDir = path.join(root, 'tests', opts.feature)
  const specFile = path.join(testDir, 'index.spec.ts')
  writeIfAllowed(
    specFile,
    renderSpecFile(opts.feature, !!opts.withLogin),
    !!opts.overwrite,
    filesWritten,
    filesSkipped,
  )

  const readmeFile = path.join(testDir, 'README.md')
  writeIfAllowed(
    readmeFile,
    renderReadme(opts.feature, owner),
    !!opts.overwrite,
    filesWritten,
    filesSkipped,
  )

  const featuresIndex = upsertFeaturesIndex(root, {
    feature: opts.feature,
    owner,
    coverage_file: path.relative(root, coverageFile),
    spec_file: path.relative(root, specFile),
    added_at: new Date().toISOString(),
  })

  return {
    feature: opts.feature,
    projectRoot: root,
    filesWritten,
    filesSkipped,
    featuresIndex,
  }
}
